# GoReleaser configuration for release-agent-team
# Documentation: https://goreleaser.com

version: 2

project_name: release-agent-team

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: release-agent-team
    main: ./cmd/releaseagent
    binary: release-agent-team
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: release-agent-team
    builds:
      - release-agent-team
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Performance
      regexp: '^perf'
      order: 2
    - title: Refactoring
      regexp: '^refactor'
      order: 3
    - title: Other
      order: 999

release:
  github:
    owner: agentplexus
    name: release-agent-team
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Tag }}

    {{ .TagSubject }}

  footer: |
    ---

    **Full Changelog**: https://github.com/agentplexus/release-agent-team/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    ```bash
    # Go install
    go install github.com/agentplexus/release-agent-team/cmd/releaseagent@{{ .Tag }}

    # Homebrew (macOS/Linux)
    brew install agentplexus/tap/release-agent-team
    ```

brews:
  - name: release-agent-team
    ids:
      - release-agent-team
    repository:
      owner: agentplexus
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/agentplexus/release-agent-team
    description: Multi-agent release preparation team for multi-language repositories
    license: MIT
    dependencies:
      - name: git
      - name: gh
    test: |
      system "#{bin}/release-agent-team", "version"
    install: |
      bin.install "release-agent-team"

announce:
  skip: true

