package actions

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// RoadmapAction generates and updates roadmaps using sroadmap.
type RoadmapAction struct{}

// Name returns the action name.
func (a *RoadmapAction) Name() string {
	return "roadmap"
}

// Run executes the roadmap action directly.
func (a *RoadmapAction) Run(dir string, opts Options) Result {
	// Check if sroadmap is available
	if !commandExists("sroadmap") {
		return Result{
			Name:    "roadmap",
			Success: false,
			Error:   fmt.Errorf("sroadmap not found in PATH"),
			Output:  "Install sroadmap: go install github.com/grokify/sroadmap/cmd/sroadmap@latest",
		}
	}

	var output strings.Builder

	// Check if ROADMAP.json exists
	roadmapJSON := filepath.Join(dir, "ROADMAP.json")
	if !fileExists(roadmapJSON) {
		return Result{
			Name:    "roadmap",
			Success: false,
			Error:   fmt.Errorf("ROADMAP.json not found"),
			Output:  "ROADMAP.json not found. Create it first.",
		}
	}

	// Step 1: Validate ROADMAP.json
	output.WriteString("Validating ROADMAP.json...\n")
	validateResult := runCommand("validate", dir, "sroadmap", "validate", "ROADMAP.json")
	if !validateResult.Success {
		return Result{
			Name:    "roadmap",
			Success: false,
			Error:   validateResult.Error,
			Output:  output.String() + validateResult.Output,
		}
	}
	output.WriteString("ROADMAP.json is valid\n")

	// If dry run, show stats and stop
	if opts.DryRun {
		output.WriteString("\nRoadmap statistics:\n")
		statsResult := runCommand("stats", dir, "sroadmap", "stats", "ROADMAP.json")
		output.WriteString(statsResult.Output)
		output.WriteString("\n\n[Dry run] Would generate ROADMAP.md\n")
		return Result{
			Name:    "roadmap",
			Success: true,
			Output:  output.String(),
		}
	}

	// Step 2: Generate ROADMAP.md
	output.WriteString("\nGenerating ROADMAP.md...\n")
	generateResult := runCommand("generate", dir, "sroadmap", "generate", "-i", "ROADMAP.json", "-o", "ROADMAP.md")
	if !generateResult.Success {
		return Result{
			Name:    "roadmap",
			Success: false,
			Error:   generateResult.Error,
			Output:  output.String() + generateResult.Output,
		}
	}
	output.WriteString("Generated ROADMAP.md\n")

	return Result{
		Name:    "roadmap",
		Success: true,
		Output:  output.String(),
	}
}

// Propose generates proposals for interactive mode.
func (a *RoadmapAction) Propose(dir string, opts Options) ([]Proposal, error) {
	// Check if sroadmap is available
	if !commandExists("sroadmap") {
		return nil, fmt.Errorf("sroadmap not found in PATH")
	}

	// Check if ROADMAP.json exists
	roadmapJSON := filepath.Join(dir, "ROADMAP.json")
	if !fileExists(roadmapJSON) {
		return nil, fmt.Errorf("ROADMAP.json not found")
	}

	// Get stats to show what will be included
	statsResult := runCommand("stats", dir, "sroadmap", "stats", "ROADMAP.json")

	// Read current ROADMAP.md if it exists
	roadmapMD := filepath.Join(dir, "ROADMAP.md")
	oldContent := ""
	if fileExists(roadmapMD) {
		content, err := os.ReadFile(roadmapMD)
		if err == nil {
			oldContent = string(content)
		}
	}

	return []Proposal{
		{
			Description: "Regenerate ROADMAP.md from ROADMAP.json",
			FilePath:    "ROADMAP.md",
			OldContent:  oldContent,
			NewContent:  "[Will be generated by sroadmap]",
			Metadata: map[string]string{
				"stats": statsResult.Output,
			},
		},
	}, nil
}

// Apply applies approved proposals.
func (a *RoadmapAction) Apply(dir string, proposals []Proposal) Result {
	// Run the action to apply changes
	return a.Run(dir, Options{DryRun: false})
}

// Validate runs sroadmap validate on ROADMAP.json.
func (a *RoadmapAction) Validate(dir string) error {
	if !commandExists("sroadmap") {
		return fmt.Errorf("sroadmap not found in PATH")
	}

	result := runCommand("validate", dir, "sroadmap", "validate", "ROADMAP.json")
	if !result.Success {
		return fmt.Errorf("validation failed: %s", result.Output)
	}

	return nil
}

// Generate runs sroadmap generate to create ROADMAP.md.
func (a *RoadmapAction) Generate(dir string) error {
	if !commandExists("sroadmap") {
		return fmt.Errorf("sroadmap not found in PATH")
	}

	result := runCommand("generate", dir, "sroadmap", "generate", "-i", "ROADMAP.json", "-o", "ROADMAP.md")
	if !result.Success {
		return result.Error
	}

	return nil
}

// Stats returns roadmap statistics.
func (a *RoadmapAction) Stats(dir string) (string, error) {
	if !commandExists("sroadmap") {
		return "", fmt.Errorf("sroadmap not found in PATH")
	}

	result := runCommand("stats", dir, "sroadmap", "stats", "ROADMAP.json")
	if !result.Success {
		return "", result.Error
	}

	return result.Output, nil
}
