# Homebrew formula for releaseagent
# This formula is auto-generated by GoReleaser
# Manual template for reference - actual formula is published to grokify/homebrew-tap

class Releaseagent < Formula
  desc "Autonomous release preparation agent for multi-language repositories"
  homepage "https://github.com/grokify/release-agent"
  license "Apache-2.0"
  version "1.0.0"

  on_macos do
    on_arm do
      url "https://github.com/grokify/release-agent/releases/download/v#{version}/releaseagent_#{version}_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"
    end
    on_intel do
      url "https://github.com/grokify/release-agent/releases/download/v#{version}/releaseagent_#{version}_darwin_x86_64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_AMD64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grokify/release-agent/releases/download/v#{version}/releaseagent_#{version}_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
    end
    on_intel do
      url "https://github.com/grokify/release-agent/releases/download/v#{version}/releaseagent_#{version}_linux_x86_64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"
    end
  end

  depends_on "git"
  depends_on "gh"

  def install
    bin.install "releaseagent"
  end

  test do
    system "#{bin}/releaseagent", "version"
  end
end
